### ISSUE TITLE
BIOS

### ISSUE THREAD

**Issue by DejanOnTheGo** [birdkiwi/H110M-PRO-VD-hackintosh#2]
Hey would you maybe share your BIOS Settings?
Thank you !

**Comment by birdkiwi** [comment]
Hi!

HPET: enabled
Intel Serial I/O: disabled

**Advanced\USB Config:** 
USB Controller: enabled
XHCI Hand off: enabled
Legacy USB Support: enabled

**Overclocking\CPU Features:** 
Intel Virtualization Tech: enabled
Intel VT-D Tech: enabled

Boot Mode: UEFI

Other is default IIRC.
